base:
  project: thyroid prediction project
  random_state: 42
  target_col: Class

data_source:
  dir: data_given
  allhyper: allhyper.data
  allhypertest: allhyper.test
  allhypo : allhypo.data
  allhypotest: allhypo.test
  thyroid0387: thyroid0387.data
  hypothyroid: hypothyroid.data
  sickeuthyroid: sick-euthyroid.data
  anntest: ann-test.data
  anntrain: ann-train.data



load_data:
  raw_dataset: data/raw

data_cleaning_processing:
  column_hyper_hypo_thy0387: ['age','sex','on_thyroxine','query_on_thyroxine','on_antithyroid_medication','sick','pregnant','thyroid_surgery','I131_treatment','query_hypothyroid','query_hyperthyroid','lithium','goitre','tumor','hypopituitary','psych','TSH_measured','TSH','T3_measured','T3','TT4_measured','TT4','T4U_measured','T4U','FTI_measured','FTI','TBG_measured','TBG','referral_source','Target']
  column_hypothy_sick:       ['Unnamed','Age','Sex','on_thyroxine','query_on_thyroxine','on_antithyroid_medication','thyroid_surgery','query_hypothyroid','query_hyperthyroid','pregnant','sick','tumor','lithium','goitre','TSH_measured','TSH','T3_measured','T3','TT4_measured','TT4','T4U_measured','T4U','FTI_measured','FTI','TBG_measured','TBG']
  columns_ann:               ["age","sex" ,"on_thyroxine", "query_on_thyroxine" ,  "on_antithyroid_medication" , "sick", "pregnant","thyroid_surgery" ,"I131_treatment"  ,"query_hypothyroid" ,"query_hyperthyroid" ,"lithium","goitre" , "tumor" ,"hypopituitary","psych","TSH"  ,"T3" ,"TT4", "T4U" ,"FTI", "Class" ]                                             
  processed_dataset: data/processed
  processed_filename: preprocessed_dataset.csv



traintestsplit:
  scaler_model_dir: saved_scaler_models
  scaler_filename: thyroid_scaler.pickle
  all_data: ['age', 'sex', 'on_thyroxine', 'query_hypothyroid', 'query_hyperthyroid',
       'psych', 'TSH_measured', 'TSH', 'T3_measured', 'T3', 'TT4_measured',
       'TT4', 'T4U_measured', 'FTI_measured', 'FTI','Class']
  train_filename: train.csv
  test_filename: test.csv
  test_size: 0.30

train_evaluate:
  selected_features: ['age', 'sex', 'on_thyroxine', 'query_hypothyroid', 'query_hyperthyroid',
       'psych', 'TSH_measured', 'TSH', 'T3_measured', 'T3', 'TT4_measured',
       'TT4', 'T4U_measured', 'FTI_measured', 'FTI']
  
  class_weight: 'balanced'
  model_filename: thyroid_model.pkl
  
reports:
  scores: reports/scores.json
  
scaler_model_dir:
  scaler_model_dirpath: saved_scaler_models
  scaler_file: thyroid_scaler.pickle
  model_file: thyroid_model.pkl